import type { Models } from "appwrite"

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types --language ts ./src/types/appwrite.ts`.

export type Clients = Models.Row & {
  name: string
  tax_id: string
  address: string
  email: string | null
}
