import type { Models } from "node-appwrite"

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types --language ts ./src/types/appwrite.ts`.

export enum InvoicesStatus {
  DRAFT = "draft",
  SENT = "sent",
  PAID = "paid",
}

export type Clients = Models.Row & {
  name: string
  tax_id: string
  address: string
  email: string | null
}

export type Invoices = Models.Row & {
  invoice_number: string
  issue_date: string
  due_date: string | null
  description: string
  subtotal: number
  vat_amount: number | null
  total: number
  status: InvoicesStatus
  client_id: Clients
  file_url: string | null
}

export type Expenses = Models.Row & {
  date: string
  supplier_id: string | null
  description: string
  category: string
  amount: number
  vat_rate: number | null
  vat_amount: number | null
  total: number
  receipt_url: string | null
  notes: string | null
}
